import React from 'react';
//import PropTypes from 'prop-types';

// import './content.css'

export default class ContentPage extends React.Component {
  constructor(props) {
    super(props);

    this.state = {}
  }
  render() {
    return (

            <div className="row">
                      <div className="col-md-8 col-md-offset-2">
                                <h1 className="centered"> Assem's Arabic Light Stemmer ( BETA )</h1>
                                <h2>Description</h2>
                                  <p> Welcome to the Arabic Light Stemming Algorithm made for <a href="http://snowballstem.org/">Snowball</a>, it's fast and can be generated in many programming languages (through Snowball).</p>

                                <h2>Demo</h2>
                                  <p>Type some Arabic text and press <b>"Stem!"</b> button or <b>"File"</b> to read from a local <b>".txt"</b> file</p>
                                  <div className="mtb">
                                      <input id="query" type="text" onChange={ () => {}}/>
                                      <button  className='btn btn-conf btn-success'>Stem!</button>
                                      <button  className="btn btn-conf btn-info">File</button>

                                      <div id="sh">
                                          <h3>Result: </h3>
                                          <div className="well centered">
                                                <div><span className="label label-default">Stats</span><span id="stats"></span></div>
                                                <br/>
                                                <ul id="result"></ul>
                                          </div>

                                      </div>
                                </div>
                                <h2>Code</h2>
                                  		  <table className="table table-striped table-bordered table-condensed">
                                          <tbody>
                                                		  <tr>
                                                    		  	<th> Programming language </th>
                                                    		  	<th> Author/Affiliation </th>
                                                    		  	<th> How to use</th>
                                                    		  	<th> Links </th>
                                                			      <th> Notes </th>
                                                		  </tr>
                                                		  <tr className="success">
                                                		  	<td> Snowball</td>
                                                		  	<td> <a href="http://www.assemchelli.com/">Assem Chelli</a></td>
                                                		  	<td> /</td>
                                                		  	<td> <a href="https://github.com/assem-ch/arabicstemmer">github</a></td>
                                                		  	<td> main </td>
                                                		  </tr>

                                                		  <tr className="">
                                                    		  	<td> Python</td>
                                                    		  	<td> Generated by Snowball  </td>
                                                    		  	<td>
                                                                  <pre className='prettyprint'>
                                                                        from snowballstemmer import stemmer
                                                                        ar_stemmer = stemmer("arabic")
                                                                        ar_stemmer.stemWord(u"فسميتموها")
                                                                  </pre>
                                                            </td>
                                                    		  	<td> <a href="/python">download</a></td>
                                                    		  	<td> </td>
                                                		  </tr>
                                                		  <tr className="">
                                                    		  	<td rowSpan="2"> JavaScript </td>
                                                    		  	<td> Generated by snowball  </td>
                                                    		  	<td></td>
                                                    		  	<td> <a href="http://snowballstem.org/js/stemmers.js">download</a></td>
                                                    		  	<td> </td>
                                                		  </tr>
                                                		  <tr className="">
                                                    		  	<td> Generated by jssnowball  </td>
                                                    		  	<td>
                                                                  <pre className='prettyprint'>
                                                                  stemmer = snowballFactory.newStemmer("arabic");
                                                                  stemmer.stem(word);
                                                                </pre>
                                                            </td>
                                                    		  	<td> <a href="/lib/snowball.babel.js">download</a></td>
                                                    		  	<td> </td>
                                                		  </tr>



                                                		  <tr className="">
                                                    		  	<td> Java</td>
                                                    		  	<td> Generated by Snowball </td>
                                                    		  	<td> /</td>
                                                    		  	<td> <a href="/java">download</a></td>
                                                    		  	<td>  </td>
                                                		  </tr>
                                                		  <tr className="">
                                                    		  	<td> C</td>
                                                    		  	<td> Generated by Snowball </td>
                                                    		  	<td> /</td>
                                                    		  	<td> <a href="/c">download</a></td>
                                                    		  	<td>  </td>
                                                		  </tr>
                                                		  <tr className="">
                                                    		  	<td> JSX </td>
                                                    		  	<td> Generated by Snowball</td>
                                                    		  	<td>
                                                                <pre className='prettyprint'>
                                                                  import "arabic-stemmer.jsx";
                                                                  var stemmer = new ArabicStemmer();
                                                                  stemmer.stemWord("فسميتموها");
                                                                </pre>
                                                            </td>

                                                    		  	<td> <a href="/jsx">download</a></td>
                                                    		  	<td>  </td>
                                                		  </tr>

                                                		  <tr className="">
                                                    		  	<td> C++</td>
                                                    		  	<td> Generated by Snowball </td>
                                                    		  	<td> /</td>
                                                    		  	<td> <a href="/cpp">download</a></td>
                                                    		  	<td>  </td>
                                                		  </tr>
                                           </tbody>
                                  		  </table>
                                        <h2>Contribute</h2>

                                        	  <p> If you have a bug or suggestion, please consider to submit a report <a href="https://github.com/assem-ch/arabicstemmer/issues/new">here</a>. Open issues are listed <a href="https://github.com/assem-ch/arabicstemmer/issues"> here</a>.
                                             </p>

                                        <h2>Contributors</h2>

                                           <ul className="menuLeft">
                                                 <li>
                                                 	<h4><a href="http://www.assemchelli.com">Assem Chelli</a><small> Algorithm, Website</small></h4>
                                                 </li>
                                                 <li>
                                                 	<h4><a href="https://github.com/kariminf">Abdelkrim Aries</a> <small> Algorithm</small></h4>
                                                 </li>
                                                 <li>
                                                 	<h4><a href="https://github.com/islamoc">Azeddine Islam Mennouchi</a> <small> Website</small></h4>
                                                 </li>
                                           </ul>
                                         <h2>Used framworks/libs</h2>

                                             <ul className="menuLeft">
                                                    <li>
                                                    	<h4><a href="https://github.com/snowballstem/snowball">snowball</a></h4>
                                                    </li>
                                                    <li>
                                                    	<h4><a href="https://github.com/mazko/jssnowball">mazko/jssnowball</a></h4>
                                                    </li>
                                                    <li>
                                                    	<h4><a href="http://getbootstrap.com/">Bootstrap</a></h4>
                                                    </li>
                                              </ul>



                      </div>
              </div>


    );
  }
}
